version: "3.5"

services:
  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-local}
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "${DB_PORT:-5432}:5432"
